//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNgheCao
    {
        public int OBJECTID { get; set; }
        public string HoVaTen { get; set; }
        public string CongNgheUngDung { get; set; }
        public string MaDoiTuong { get; set; }
        public string SoDienThoai { get; set; }
        public CongNgheCao(BVTV.Entity.CONGNGHECAO obj)
        {
            this.CongNgheUngDung = obj.CongNgheUngDung;
            this.HoVaTen = obj.HoVaTen;
            this.MaDoiTuong = obj.MaDoiTuong;
            this.OBJECTID = obj.OBJECTID;
            this.SoDienThoai = obj.SoDienThoai;
        }
    }
}
