//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiongCayTrong
    {
        public int OBJECTID { get; set; }
        public string MaGiongCayTrong { get; set; }
        public string LoaiCayTrong { get; set; }
        public string GiongCayTrong1 { get; set; }
    }
}
