//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimDuong
    {
        public int OBJECTID { get; set; }
        public string maNhanDang { get; set; }
        public System.DateTime ngayThuNhan { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string maDoiTuong { get; set; }
        public short loaiDuongBo { get; set; }
        public short loaiChatLieuTraiMat { get; set; }
        public short loaiHienTrangSuDung { get; set; }
        public short loaiKetCau { get; set; }
        public decimal doRong { get; set; }
        public string ten { get; set; }
        public string tenTuyen1 { get; set; }
        public string tenTuyen2 { get; set; }
        public string tenTuyen3 { get; set; }
        public string MaHuyenTP { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
