//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a34
    {
        public int OBJECTID { get; set; }
        public string MaDoiTuong { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> Nam { get; set; }
        public Nullable<short> NhomCayTrong { get; set; }
        public string LoaiCayTrong { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
