//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a49
    {
        public int OBJECTID { get; set; }
        public string MaDoiTuong { get; set; }
        public Nullable<short> NhomCayTrong { get; set; }
        public string LoaiCayTrong { get; set; }
        public Nullable<decimal> DienTichTrong { get; set; }
        public Nullable<short> TinhHinhUngDungCongNghe { get; set; }
        public string ToChucCaNhanQuanLy { get; set; }
        public string TinhTrangThuHoach { get; set; }
        public string GhiChu { get; set; }
        public string MaLoaiCayTrong { get; set; }
        public Nullable<short> PhuongThucTrong { get; set; }
        public Nullable<short> ThoiVuTrongTrot { get; set; }
        public string MatDoCayTrong { get; set; }
        public string TenGiongCayTrong { get; set; }
        public string MaHuyenTP { get; set; }
        public Nullable<int> GiaiDoanSinhTruong { get; set; }
        public string MaDuong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
