//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a50
    {
        public int OBJECTID { get; set; }
        public string MaNhanDang { get; set; }
        public Nullable<decimal> Shape_Leng { get; set; }
        public string MaPhuongXa { get; set; }
        public string MaHuyenTP { get; set; }
        public string GhiChu { get; set; }
        public Nullable<short> DonViQuanLy { get; set; }
        public Nullable<short> DonViCapNhat { get; set; }
        public string MaDoiTuong { get; set; }
        public string MaDonViHanhChinh { get; set; }
        public string DanhTuChung { get; set; }
        public string DiaDanh { get; set; }
        public string DoiTuong { get; set; }
        public Nullable<System.DateTime> NgayThuNhan { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public string TenXa { get; set; }
        public string TenHuyen { get; set; }
        public string CheckTool { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
