//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a57
    {
        public int OBJECTID { get; set; }
        public string HoVaTen { get; set; }
        public string CongNgheUngDung { get; set; }
        public string MaDoiTuong { get; set; }
        public string SoDienThoai { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
