//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT
    {
        public int OBJECTID { get; set; }
        public string NguoiDung { get; set; }
        public string ThaoTac { get; set; }
        public string MaDoiTuong { get; set; }
        public string LopDuLieu { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
