//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaoVeThucVatEntities : DbContext
    {
        public BaoVeThucVatEntities()
            : base("name=BaoVeThucVatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<a47> a47 { get; set; }
        public virtual DbSet<a48> a48 { get; set; }
        public virtual DbSet<a49> a49 { get; set; }
        public virtual DbSet<a50> a50 { get; set; }
        public virtual DbSet<a51> a51 { get; set; }
        public virtual DbSet<a52> a52 { get; set; }
        public virtual DbSet<a53> a53 { get; set; }
        public virtual DbSet<a54> a54 { get; set; }
        public virtual DbSet<a55> a55 { get; set; }
        public virtual DbSet<a56> a56 { get; set; }
        public virtual DbSet<a57> a57 { get; set; }
        public virtual DbSet<a58> a58 { get; set; }
        public virtual DbSet<a59> a59 { get; set; }
        public virtual DbSet<a60> a60 { get; set; }
        public virtual DbSet<a63> a63 { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<D47> D47 { get; set; }
        public virtual DbSet<D48> D48 { get; set; }
        public virtual DbSet<D49> D49 { get; set; }
        public virtual DbSet<D50> D50 { get; set; }
        public virtual DbSet<D51> D51 { get; set; }
        public virtual DbSet<D52> D52 { get; set; }
        public virtual DbSet<D53> D53 { get; set; }
        public virtual DbSet<D54> D54 { get; set; }
        public virtual DbSet<D55> D55 { get; set; }
        public virtual DbSet<D56> D56 { get; set; }
        public virtual DbSet<D57> D57 { get; set; }
        public virtual DbSet<D58> D58 { get; set; }
        public virtual DbSet<D59> D59 { get; set; }
        public virtual DbSet<D60> D60 { get; set; }
        public virtual DbSet<D63> D63 { get; set; }
        public virtual DbSet<DanhMucCayTrongRauMau> DanhMucCayTrongRauMaus { get; set; }
        public virtual DbSet<DOANHNGHIEP> DOANHNGHIEPs { get; set; }
        public virtual DbSet<GDB_ITEMRELATIONSHIPS> GDB_ITEMRELATIONSHIPS { get; set; }
        public virtual DbSet<GDB_ITEMS> GDB_ITEMS { get; set; }
        public virtual DbSet<HANHCHINHHUYEN> HANHCHINHHUYENs { get; set; }
        public virtual DbSet<i2> i2 { get; set; }
        public virtual DbSet<i3> i3 { get; set; }
        public virtual DbSet<i4> i4 { get; set; }
        public virtual DbSet<i47> i47 { get; set; }
        public virtual DbSet<i48> i48 { get; set; }
        public virtual DbSet<i49> i49 { get; set; }
        public virtual DbSet<i5> i5 { get; set; }
        public virtual DbSet<i50> i50 { get; set; }
        public virtual DbSet<i51> i51 { get; set; }
        public virtual DbSet<i52> i52 { get; set; }
        public virtual DbSet<i53> i53 { get; set; }
        public virtual DbSet<i54> i54 { get; set; }
        public virtual DbSet<i55> i55 { get; set; }
        public virtual DbSet<i56> i56 { get; set; }
        public virtual DbSet<i57> i57 { get; set; }
        public virtual DbSet<i58> i58 { get; set; }
        public virtual DbSet<i59> i59 { get; set; }
        public virtual DbSet<i6> i6 { get; set; }
        public virtual DbSet<i60> i60 { get; set; }
        public virtual DbSet<i61> i61 { get; set; }
        public virtual DbSet<i62> i62 { get; set; }
        public virtual DbSet<i63> i63 { get; set; }
        public virtual DbSet<MATDUONGBO> MATDUONGBOes { get; set; }
        public virtual DbSet<NhomCayTrong> NhomCayTrongs { get; set; }
        public virtual DbSet<PHUBEMAT> PHUBEMATs { get; set; }
        public virtual DbSet<QUYHOACHSUDUNGDAT> QUYHOACHSUDUNGDATs { get; set; }
        public virtual DbSet<RANHGIOIHANHCHINH> RANHGIOIHANHCHINHs { get; set; }
        public virtual DbSet<SAUBENH> SAUBENHs { get; set; }
        public virtual DbSet<SDE_archives> SDE_archives { get; set; }
        public virtual DbSet<SDE_column_registry> SDE_column_registry { get; set; }
        public virtual DbSet<SDE_dbtune> SDE_dbtune { get; set; }
        public virtual DbSet<SDE_geometry_columns> SDE_geometry_columns { get; set; }
        public virtual DbSet<SDE_GEOMETRY1> SDE_GEOMETRY1 { get; set; }
        public virtual DbSet<SDE_GEOMETRY34> SDE_GEOMETRY34 { get; set; }
        public virtual DbSet<SDE_GEOMETRY35> SDE_GEOMETRY35 { get; set; }
        public virtual DbSet<SDE_GEOMETRY36> SDE_GEOMETRY36 { get; set; }
        public virtual DbSet<SDE_GEOMETRY37> SDE_GEOMETRY37 { get; set; }
        public virtual DbSet<SDE_GEOMETRY38> SDE_GEOMETRY38 { get; set; }
        public virtual DbSet<SDE_GEOMETRY39> SDE_GEOMETRY39 { get; set; }
        public virtual DbSet<SDE_GEOMETRY40> SDE_GEOMETRY40 { get; set; }
        public virtual DbSet<SDE_GEOMETRY41> SDE_GEOMETRY41 { get; set; }
        public virtual DbSet<SDE_GEOMETRY42> SDE_GEOMETRY42 { get; set; }
        public virtual DbSet<SDE_GEOMETRY43> SDE_GEOMETRY43 { get; set; }
        public virtual DbSet<SDE_layer_locks> SDE_layer_locks { get; set; }
        public virtual DbSet<SDE_layer_stats> SDE_layer_stats { get; set; }
        public virtual DbSet<SDE_layers> SDE_layers { get; set; }
        public virtual DbSet<SDE_lineages_modified> SDE_lineages_modified { get; set; }
        public virtual DbSet<SDE_locators> SDE_locators { get; set; }
        public virtual DbSet<SDE_logfile_pool> SDE_logfile_pool { get; set; }
        public virtual DbSet<SDE_metadata> SDE_metadata { get; set; }
        public virtual DbSet<SDE_object_ids> SDE_object_ids { get; set; }
        public virtual DbSet<SDE_object_locks> SDE_object_locks { get; set; }
        public virtual DbSet<SDE_process_information> SDE_process_information { get; set; }
        public virtual DbSet<SDE_raster_columns> SDE_raster_columns { get; set; }
        public virtual DbSet<SDE_server_config> SDE_server_config { get; set; }
        public virtual DbSet<SDE_spatial_references> SDE_spatial_references { get; set; }
        public virtual DbSet<SDE_state_lineages> SDE_state_lineages { get; set; }
        public virtual DbSet<SDE_state_locks> SDE_state_locks { get; set; }
        public virtual DbSet<SDE_states> SDE_states { get; set; }
        public virtual DbSet<SDE_table_locks> SDE_table_locks { get; set; }
        public virtual DbSet<SDE_table_registry> SDE_table_registry { get; set; }
        public virtual DbSet<SDE_tables_modified> SDE_tables_modified { get; set; }
        public virtual DbSet<SDE_version> SDE_version { get; set; }
        public virtual DbSet<SDE_versions> SDE_versions { get; set; }
        public virtual DbSet<SDE_xml_columns> SDE_xml_columns { get; set; }
        public virtual DbSet<SDE_xml_index_tags> SDE_xml_index_tags { get; set; }
        public virtual DbSet<SDE_xml_indexes> SDE_xml_indexes { get; set; }
        public virtual DbSet<SONGHO> SONGHOes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIMDUONG> TIMDUONGs { get; set; }
        public virtual DbSet<TRONGTROT> TRONGTROTs { get; set; }
        public virtual DbSet<AUDIT> AUDITs { get; set; }
        public virtual DbSet<CONDUONG> CONDUONGs { get; set; }
        public virtual DbSet<CONGNGHECAO> CONGNGHECAOs { get; set; }
        public virtual DbSet<GDB_ITEMRELATIONSHIPTYPES> GDB_ITEMRELATIONSHIPTYPES { get; set; }
        public virtual DbSet<GDB_ITEMTYPES> GDB_ITEMTYPES { get; set; }
        public virtual DbSet<GDB_REPLICALOG> GDB_REPLICALOG { get; set; }
        public virtual DbSet<GDB_TABLES_LAST_MODIFIED> GDB_TABLES_LAST_MODIFIED { get; set; }
        public virtual DbSet<GIAPHANBON_THUOCBVTT_NONGSAN_GIONG> GIAPHANBON_THUOCBVTT_NONGSAN_GIONG { get; set; }
        public virtual DbSet<GIONGCAYTRONG> GIONGCAYTRONGs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NGUOIDUNG_NHOMQUYEN> NGUOIDUNG_NHOMQUYEN { get; set; }
        public virtual DbSet<NHOMQUYEN> NHOMQUYENs { get; set; }
        public virtual DbSet<SAUBENHGAYHAI> SAUBENHGAYHAIs { get; set; }
        public virtual DbSet<THOIGIANSANXUATTRONGTROT> THOIGIANSANXUATTRONGTROTs { get; set; }
        public virtual DbSet<News> News { get; set; }
    }
}
