//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class D54
    {
        public long SDE_STATE_ID { get; set; }
        public int SDE_DELETES_ROW_ID { get; set; }
        public long DELETED_AT { get; set; }
    }
}
