//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHNGHIEP
    {
        public int OBJECTID { get; set; }
        public string MaDoanhNghiep { get; set; }
        public string NguoiDaiDienDoanhNghiep { get; set; }
        public string SoNha { get; set; }
        public string TenDuong { get; set; }
        public string PhuongXa { get; set; }
        public string QuanHuyen { get; set; }
        public string Website { get; set; }
        public string DiaChiKho { get; set; }
        public string TenCBPhuTrach { get; set; }
        public Nullable<short> DienThoai { get; set; }
        public Nullable<short> Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> LoaiDonViSXKD { get; set; }
        public Nullable<short> DanhMucSanPham { get; set; }
        public byte[] GiayPhepSXKD { get; set; }
        public Nullable<short> SanLuongTrongNam { get; set; }
        public byte[] GiayCNDuDieuKienSXKD { get; set; }
        public Nullable<short> DanhGiaXepLoai { get; set; }
        public Nullable<System.DateTime> ThoiGianThanhTra { get; set; }
        public Nullable<short> NguyenNhanThanhTra { get; set; }
        public Nullable<short> HinhThucPhat { get; set; }
        public Nullable<short> MucPhat { get; set; }
        public string MaHoSoLuuTru { get; set; }
        public Nullable<short> SoLanViPham { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
