//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDB_ITEMRELATIONSHIPTYPES
    {
        public int ObjectID { get; set; }
        public System.Guid UUID { get; set; }
        public string Name { get; set; }
        public string ForwardLabel { get; set; }
        public string BackwardLabel { get; set; }
        public System.Guid OrigItemTypeID { get; set; }
        public System.Guid DestItemTypeID { get; set; }
        public Nullable<short> IsContainment { get; set; }
    }
}
