//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDB_ITEMS
    {
        public int ObjectID { get; set; }
        public System.Guid UUID { get; set; }
        public System.Guid Type { get; set; }
        public string Name { get; set; }
        public string PhysicalName { get; set; }
        public string Path { get; set; }
        public string Url { get; set; }
        public Nullable<int> Properties { get; set; }
        public byte[] Defaults { get; set; }
        public Nullable<int> DatasetSubtype1 { get; set; }
        public Nullable<int> DatasetSubtype2 { get; set; }
        public string DatasetInfo1 { get; set; }
        public string DatasetInfo2 { get; set; }
        public string Definition { get; set; }
        public string Documentation { get; set; }
        public string ItemInfo { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
