//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDB_ITEMRELATIONSHIPS
    {
        public int ObjectID { get; set; }
        public System.Guid UUID { get; set; }
        public System.Guid Type { get; set; }
        public System.Guid OriginID { get; set; }
        public System.Guid DestID { get; set; }
        public Nullable<int> Properties { get; set; }
        public string Attributes { get; set; }
    }
}
