//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDB_REPLICALOG
    {
        public int ID { get; set; }
        public int ReplicaID { get; set; }
        public int Event { get; set; }
        public int ErrorCode { get; set; }
        public System.DateTime LogDate { get; set; }
        public int SourceBeginGen { get; set; }
        public int SourceEndGen { get; set; }
        public int TargetGen { get; set; }
    }
}
