//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAPHANBON_THUOCBVTT_NONGSAN_GIONG
    {
        public int OBJECTID { get; set; }
        public Nullable<short> NhomGia { get; set; }
        public Nullable<short> TenDoiTuong { get; set; }
        public string Gia { get; set; }
    }
}
