//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class i58
    {
        public int id_type { get; set; }
        public int base_id { get; set; }
        public int num_ids { get; set; }
        public Nullable<int> last_id { get; set; }
    }
}
