//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public int IDNguoiDung { get; set; }
        public string NguoiDung1 { get; set; }
        public string HoTen { get; set; }
        public string MatKhau { get; set; }
        public string PhienBan { get; set; }
    }
}
