//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUBEMAT
    {
        public int OBJECTID { get; set; }
        public string maNhanDang { get; set; }
        public Nullable<System.DateTime> ngayThuNhan { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string maDoiTuong { get; set; }
        public string ten { get; set; }
        public Nullable<int> loaiPhuBeMat { get; set; }
        public Nullable<short> doiTuong { get; set; }
        public string ghichu { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
