//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYHOACHSUDUNGDAT
    {
        public int OBJECTID { get; set; }
        public string KyHieuLoaiDat { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public string GhiChu { get; set; }
        public Nullable<short> GiaiDoanQuyHoach { get; set; }
        public string MaDoiTuong { get; set; }
        public string MaHuyenTP { get; set; }
        public Nullable<short> MucDichSuDungDat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
