//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAUBENH
    {
        public int OBJECTID { get; set; }
        public Nullable<short> NhomCayTrong { get; set; }
        public string LoaiCayTrong { get; set; }
        public string TenSauBenhGayHai { get; set; }
        public Nullable<short> MatDoSauBenhGayHai { get; set; }
        public Nullable<short> PhamViAnhHuong { get; set; }
        public Nullable<short> MucDoAnhHuong { get; set; }
        public Nullable<short> ThoiGianGayHai { get; set; }
        public Nullable<short> CapDoGayHai { get; set; }
        public Nullable<short> TinhHinhKiemSoatDichBenh { get; set; }
        public Nullable<short> MucDoKiemSoat { get; set; }
        public string BienPhapXuLy { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public string MaHuyenTP { get; set; }
        public string GiaiDoanSinhTruong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string MaSauBenh { get; set; }
        public Nullable<System.DateTime> NgayXayRa { get; set; }
        public string SauBenhGayHai { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
