//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAUBENHGAYHAI
    {
        public int OBJECTID { get; set; }
        public string MaSauBenh { get; set; }
        public Nullable<short> NhomCayTrong { get; set; }
        public string LoaiCayTrong { get; set; }
        public string SauBenhGayHai1 { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> Nam { get; set; }
    }
}
