//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_archives
    {
        public int archiving_regid { get; set; }
        public int history_regid { get; set; }
        public string from_date { get; set; }
        public string to_date { get; set; }
        public long archive_date { get; set; }
        public long archive_flags { get; set; }
    
        public virtual SDE_table_registry SDE_table_registry { get; set; }
        public virtual SDE_table_registry SDE_table_registry1 { get; set; }
    }
}
