//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_process_information
    {
        public int sde_id { get; set; }
        public int spid { get; set; }
        public int server_id { get; set; }
        public System.DateTime start_time { get; set; }
        public int rcount { get; set; }
        public int wcount { get; set; }
        public int opcount { get; set; }
        public int numlocks { get; set; }
        public int fb_partial { get; set; }
        public int fb_count { get; set; }
        public int fb_fcount { get; set; }
        public int fb_kbytes { get; set; }
        public string owner { get; set; }
        public string direct_connect { get; set; }
        public string sysname { get; set; }
        public string nodename { get; set; }
        public string xdr_needed { get; set; }
        public string table_name { get; set; }
    }
}
