//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_versions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SDE_versions()
        {
            this.SDE_layer_stats = new HashSet<SDE_layer_stats>();
        }
    
        public string name { get; set; }
        public string owner { get; set; }
        public int version_id { get; set; }
        public int status { get; set; }
        public long state_id { get; set; }
        public string description { get; set; }
        public string parent_name { get; set; }
        public string parent_owner { get; set; }
        public Nullable<int> parent_version_id { get; set; }
        public System.DateTime creation_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDE_layer_stats> SDE_layer_stats { get; set; }
    }
}
