//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_layer_locks
    {
        public int sde_id { get; set; }
        public int layer_id { get; set; }
        public string autolock { get; set; }
        public string lock_type { get; set; }
        public System.DateTime lock_time { get; set; }
        public Nullable<long> minx { get; set; }
        public Nullable<long> miny { get; set; }
        public Nullable<long> maxx { get; set; }
        public Nullable<long> maxy { get; set; }
    }
}
