//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_column_registry
    {
        public string database_name { get; set; }
        public string table_name { get; set; }
        public string owner { get; set; }
        public string column_name { get; set; }
        public int sde_type { get; set; }
        public Nullable<int> column_size { get; set; }
        public Nullable<int> decimal_digits { get; set; }
        public string description { get; set; }
        public int object_flags { get; set; }
        public Nullable<int> object_id { get; set; }
    }
}
