//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_geometry_columns
    {
        public string f_table_catalog { get; set; }
        public string f_table_schema { get; set; }
        public string f_table_name { get; set; }
        public string f_geometry_column { get; set; }
        public string g_table_catalog { get; set; }
        public string g_table_schema { get; set; }
        public string g_table_name { get; set; }
        public Nullable<int> storage_type { get; set; }
        public Nullable<int> geometry_type { get; set; }
        public Nullable<int> coord_dimension { get; set; }
        public Nullable<int> max_ppr { get; set; }
        public int srid { get; set; }
    
        public virtual SDE_spatial_references SDE_spatial_references { get; set; }
    }
}
