//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_xml_columns
    {
        public int column_id { get; set; }
        public int registration_id { get; set; }
        public string column_name { get; set; }
        public Nullable<int> index_id { get; set; }
        public Nullable<int> minimum_id { get; set; }
        public string config_keyword { get; set; }
        public int xflags { get; set; }
    
        public virtual SDE_table_registry SDE_table_registry { get; set; }
        public virtual SDE_xml_indexes SDE_xml_indexes { get; set; }
    }
}
