//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_metadata
    {
        public int record_id { get; set; }
        public string object_database { get; set; }
        public string object_name { get; set; }
        public string object_owner { get; set; }
        public int object_type { get; set; }
        public string class_name { get; set; }
        public string property { get; set; }
        public string prop_value { get; set; }
        public string description { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
