//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_object_locks
    {
        public int sde_id { get; set; }
        public int object_id { get; set; }
        public int object_type { get; set; }
        public int application_id { get; set; }
        public string autolock { get; set; }
        public string lock_type { get; set; }
        public System.DateTime lock_time { get; set; }
    }
}
