//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_locators
    {
        public int locator_id { get; set; }
        public string name { get; set; }
        public string owner { get; set; }
        public string category { get; set; }
        public int type { get; set; }
        public string description { get; set; }
    }
}
