//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDE_version
    {
        public int MAJOR { get; set; }
        public int MINOR { get; set; }
        public int BUGFIX { get; set; }
        public string DESCRIPTION { get; set; }
        public int RELEASE { get; set; }
        public int SDESVR_REL_LOW { get; set; }
    }
}
