//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVTV.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONGHO
    {
        public int OBJECTID { get; set; }
        public string maNhanDang { get; set; }
        public System.DateTime ngayThuNhan { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string maDoiTuong { get; set; }
        public short loaiTrangThaiNuocMat { get; set; }
        public string danhTuChung { get; set; }
        public string diaDanh { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
